---
title: Kamil Rudnicki Personal Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: post
markdown: kramdown
highlighter: pygments
pygments: true
permalink: pretty
description: A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a>
  theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo"
  target="_blank">@mdo</a>.
url: https://kamilrudnicki.com
baseurl: ''
paginate: 5
plugins:
- jekyll-paginate
version: 2.1.0
github:
  repo: https://github.com/poole/hyde
